name: CI/CD Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  ci-cd:
    uses: rcg-enterprise/DevOps-Pipelines/.github/workflows/dev-cicd-gradle.yml@master
    secrets: inherit
    with:
      image: change-me
